from __future__ import annotations

from collections.abc import Iterable
from typing import Any, Literal, Protocol, runtime_checkable

import pyarrow as pa


@runtime_checkable
class ObjectStore(Protocol):
    """Bucket/key blob storage. Local: MinIO. Cloud: S3, ADLS, GCS."""

    def ensure_bucket(self, bucket: str) -> None: ...
    def put_bytes(self, bucket: str, key: str, data: bytes) -> None: ...
    def get_bytes(self, bucket: str, key: str) -> bytes: ...
    def exists(self, bucket: str, key: str) -> bool: ...
    def list(self, bucket: str, prefix: str = "") -> list[str]: ...
    def delete(self, bucket: str, key: str) -> None: ...
    def uri(self, bucket: str, key: str = "") -> str: ...
    def storage_options(self) -> dict[str, str]:
        """Options for engines that read the store directly (DuckDB httpfs, delta-rs)."""
        ...

    def health(self) -> bool: ...


@runtime_checkable
class QueryEngine(Protocol):
    """SQL over lake data. Local: DuckDB. Cloud: Snowflake, Databricks, BigQuery, Trino."""

    def query(self, sql: str, params: list[Any] | None = None) -> pa.Table: ...
    def health(self) -> bool: ...


@runtime_checkable
class TableFormat(Protocol):
    """Transactional tables on the object store. Local: Delta Lake. Later: Iceberg."""

    def write(self, table: pa.Table, uri: str, mode: Literal["append", "overwrite"] = "append") -> int: ...
    def merge(self, table: pa.Table, uri: str, keys: list[str]) -> int: ...
    def read(self, uri: str, version: int | None = None) -> pa.Table: ...
    def history(self, uri: str) -> list[dict[str, Any]]: ...


@runtime_checkable
class ServingStore(Protocol):
    """Relational copy of gold data for BI/direct SQL. Local: Postgres `serving` DB."""

    def upsert(self, schema: str, table: str, rows: pa.Table, keys: list[str]) -> int: ...
    def replace(self, schema: str, table: str, rows: pa.Table) -> int: ...
    def grant_read(self, schema: str, table: str, role: str) -> None: ...


def iter_batches(table: pa.Table, size: int = 50_000) -> Iterable[pa.RecordBatch]:
    return table.to_batches(max_chunksize=size)
