"""phase 1b streams and alerts

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26 15:37:34.704559
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("target", sa.String(length=512), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "details", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index("ix_alerts_open", "alerts", ["kind", "target", "resolved_at"], unique=False)
    op.create_table(
        "webhook_keys",
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("hint", sa.String(length=8), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
            name=op.f("fk_webhook_keys_connection_id_connections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("connection_id", name=op.f("pk_webhook_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_webhook_keys_key_hash")),
    )
    op.create_table(
        "stream_metrics",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("minute", sa.DateTime(timezone=True), nullable=False),
        sa.Column("records", sa.BigInteger(), nullable=False),
        sa.Column("batches", sa.Integer(), nullable=False),
        sa.Column("dlq", sa.Integer(), nullable=False),
        sa.Column("latency_p50_ms", sa.BigInteger(), nullable=True),
        sa.Column("latency_p95_ms", sa.BigInteger(), nullable=True),
        sa.Column("lag", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["ingestion_jobs.id"], name=op.f("fk_stream_metrics_job_id_ingestion_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("job_id", "minute", name=op.f("pk_stream_metrics")),
    )
    op.create_table(
        "stream_state",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("desired", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("connector_name", sa.String(length=255), nullable=True),
        sa.Column(
            "topics", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "key_columns", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("worker", sa.String(length=128), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_batch_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "metrics", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "totals", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["ingestion_jobs.id"], name=op.f("fk_stream_state_job_id_ingestion_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("job_id", name=op.f("pk_stream_state")),
    )
    op.add_column("datasets", sa.Column("freshness_sla_minutes", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("datasets", "freshness_sla_minutes")
    op.drop_table("stream_state")
    op.drop_table("stream_metrics")
    op.drop_table("webhook_keys")
    op.drop_index("ix_alerts_open", table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
