"""phase 2 vault and transform

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-26 16:57:20.489559
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipelines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "models", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "schedule", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "trigger_datasets",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipelines")),
        sa.UniqueConstraint("name", name=op.f("uq_pipelines_name")),
    )
    op.create_table(
        "transform_models",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("layer", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("sql", sa.Text(), nullable=False),
        sa.Column(
            "config", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("owner", sa.String(length=128), nullable=True),
        sa.Column("created_by", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transform_models")),
        sa.UniqueConstraint("name", name=op.f("uq_transform_models_name")),
    )
    op.create_table(
        "vault_objects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "definition", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vault_objects")),
        sa.UniqueConstraint("name", name=op.f("uq_vault_objects_name")),
    )
    op.create_table(
        "transform_model_versions",
        sa.Column("model_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("sql", sa.Text(), nullable=False),
        sa.Column(
            "config", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("created_by", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["transform_models.id"],
            name=op.f("fk_transform_model_versions_model_id_transform_models"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("model_id", "version", name=op.f("pk_transform_model_versions")),
    )
    op.create_table(
        "transform_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("target", sa.String(length=256), nullable=False),
        sa.Column("pipeline_id", sa.UUID(), nullable=True),
        sa.Column("parent_run_id", sa.UUID(), nullable=True),
        sa.Column("trigger", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("rows_written", sa.BigInteger(), nullable=False),
        sa.Column("table_version", sa.BigInteger(), nullable=True),
        sa.Column("lineage_run_id", sa.String(length=64), nullable=True),
        sa.Column(
            "details", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pipeline_id"], ["pipelines.id"], name=op.f("fk_transform_runs_pipeline_id_pipelines"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transform_runs")),
    )
    op.create_index(op.f("ix_transform_runs_parent_run_id"), "transform_runs", ["parent_run_id"], unique=False)
    op.create_index(op.f("ix_transform_runs_pipeline_id"), "transform_runs", ["pipeline_id"], unique=False)
    op.create_index(op.f("ix_transform_runs_started_at"), "transform_runs", ["started_at"], unique=False)
    op.create_index("ix_transform_runs_target", "transform_runs", ["kind", "target", "started_at"], unique=False)
    op.create_table(
        "vault_mappings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_layer", sa.String(length=16), nullable=False),
        sa.Column("source_dataset", sa.String(length=256), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column(
            "keys", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "attributes", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("record_source", sa.String(length=256), nullable=True),
        sa.Column("ingestion_job_id", sa.UUID(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingestion_job_id"],
            ["ingestion_jobs.id"],
            name=op.f("fk_vault_mappings_ingestion_job_id_ingestion_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["vault_objects.id"],
            name=op.f("fk_vault_mappings_target_id_vault_objects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vault_mappings")),
    )
    op.create_index(op.f("ix_vault_mappings_ingestion_job_id"), "vault_mappings", ["ingestion_job_id"], unique=False)
    op.create_index(op.f("ix_vault_mappings_target_id"), "vault_mappings", ["target_id"], unique=False)
    op.create_index(
        "uq_vault_mappings_source_target",
        "vault_mappings",
        ["source_layer", "source_dataset", "target_id"],
        unique=True,
    )
    op.create_table(
        "vault_load_state",
        sa.Column("mapping_id", sa.UUID(), nullable=False),
        sa.Column("high_water", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_loaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_rows", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mapping_id"],
            ["vault_mappings.id"],
            name=op.f("fk_vault_load_state_mapping_id_vault_mappings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("mapping_id", name=op.f("pk_vault_load_state")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vault_load_state")
    op.drop_index("uq_vault_mappings_source_target", table_name="vault_mappings")
    op.drop_index(op.f("ix_vault_mappings_target_id"), table_name="vault_mappings")
    op.drop_index(op.f("ix_vault_mappings_ingestion_job_id"), table_name="vault_mappings")
    op.drop_table("vault_mappings")
    op.drop_index("ix_transform_runs_target", table_name="transform_runs")
    op.drop_index(op.f("ix_transform_runs_started_at"), table_name="transform_runs")
    op.drop_index(op.f("ix_transform_runs_pipeline_id"), table_name="transform_runs")
    op.drop_index(op.f("ix_transform_runs_parent_run_id"), table_name="transform_runs")
    op.drop_table("transform_runs")
    op.drop_table("transform_model_versions")
    op.drop_table("vault_objects")
    op.drop_table("transform_models")
    op.drop_table("pipelines")
    # ### end Alembic commands ###
