"""phase 3 quality and governance

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-26 21:17:05.137399
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_grants",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("target_type", sa.String(length=16), nullable=False),
        sa.Column("target", sa.String(length=256), nullable=False),
        sa.Column("principal_type", sa.String(length=16), nullable=False),
        sa.Column("principal", sa.String(length=128), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_grants")),
    )
    op.create_index(
        "uq_access_grants", "access_grants", ["target_type", "target", "principal_type", "principal"], unique=True
    )
    op.create_table(
        "dq_scorecards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "rule_ids", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "schedule", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("degradation_pct", sa.Double(), nullable=False),
        sa.Column("baseline_runs", sa.Integer(), nullable=False),
        sa.Column("owner", sa.String(length=128), nullable=True),
        sa.Column("created_by", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dq_scorecards")),
        sa.UniqueConstraint("name", name=op.f("uq_dq_scorecards_name")),
    )
    op.create_table(
        "glossary_terms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column(
            "synonyms", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("domain", sa.String(length=128), nullable=True),
        sa.Column("owner", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_glossary_terms")),
        sa.UniqueConstraint("name", name=op.f("uq_glossary_terms_name")),
    )
    op.create_table(
        "notification_channels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column(
            "config", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "kinds", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("min_severity", sa.String(length=16), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_channels")),
        sa.UniqueConstraint("name", name=op.f("uq_notification_channels_name")),
    )
    op.create_table(
        "tags",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_tags")),
    )
    op.create_table(
        "dq_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("column", sa.String(length=256), nullable=True),
        sa.Column("rule_type", sa.String(length=32), nullable=False),
        sa.Column(
            "params", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("dimension", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("threshold", sa.Double(), nullable=False),
        sa.Column("run_on_load", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owner", sa.String(length=128), nullable=True),
        sa.Column("created_by", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["datasets.id"], name=op.f("fk_dq_rules_dataset_id_datasets"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dq_rules")),
        sa.UniqueConstraint("name", name=op.f("uq_dq_rules_name")),
    )
    op.create_index(op.f("ix_dq_rules_dataset_id"), "dq_rules", ["dataset_id"], unique=False)
    op.create_table(
        "dq_scorecard_results",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("scorecard_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("score", sa.Double(), nullable=True),
        sa.Column(
            "dimensions", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("baseline", sa.Double(), nullable=True),
        sa.Column("degraded", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scorecard_id"],
            ["dq_scorecards.id"],
            name=op.f("fk_dq_scorecard_results_scorecard_id_dq_scorecards"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dq_scorecard_results")),
    )
    op.create_index("ix_dq_scorecard_results_card_ts", "dq_scorecard_results", ["scorecard_id", "ts"], unique=False)
    op.create_table(
        "glossary_links",
        sa.Column("term_id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("column", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["datasets.id"], name=op.f("fk_glossary_links_dataset_id_datasets"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["glossary_terms.id"],
            name=op.f("fk_glossary_links_term_id_glossary_terms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("term_id", "dataset_id", "column", name=op.f("pk_glossary_links")),
    )
    op.create_table(
        "masking_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("tag", sa.String(length=128), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column(
            "exempt_roles",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tag"], ["tags.name"], name=op.f("fk_masking_policies_tag_tags"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_masking_policies")),
        sa.UniqueConstraint("name", name=op.f("uq_masking_policies_name")),
    )
    op.create_index(op.f("ix_masking_policies_tag"), "masking_policies", ["tag"], unique=False)
    op.create_table(
        "row_filters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("predicate", sa.Text(), nullable=False),
        sa.Column(
            "exempt_roles",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["datasets.id"], name=op.f("fk_row_filters_dataset_id_datasets"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_row_filters")),
        sa.UniqueConstraint("name", name=op.f("uq_row_filters_name")),
    )
    op.create_index(op.f("ix_row_filters_dataset_id"), "row_filters", ["dataset_id"], unique=False)
    op.create_table(
        "tag_assignments",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("tag", sa.String(length=128), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("column", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Double(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("assigned_by", sa.String(length=128), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["datasets.id"], name=op.f("fk_tag_assignments_dataset_id_datasets"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tag"], ["tags.name"], name=op.f("fk_tag_assignments_tag_tags"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tag_assignments")),
    )
    op.create_index(op.f("ix_tag_assignments_dataset_id"), "tag_assignments", ["dataset_id"], unique=False)
    op.create_index(op.f("ix_tag_assignments_tag"), "tag_assignments", ["tag"], unique=False)
    op.create_index("uq_tag_assignments_target", "tag_assignments", ["tag", "dataset_id", "column"], unique=True)
    op.create_table(
        "dq_results",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("trigger", sa.String(length=256), nullable=False),
        sa.Column("rows_checked", sa.BigInteger(), nullable=False),
        sa.Column("rows_failed", sa.BigInteger(), nullable=False),
        sa.Column("score", sa.Double(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("table_version", sa.BigInteger(), nullable=True),
        sa.Column(
            "sample", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rule_id"], ["dq_rules.id"], name=op.f("fk_dq_results_rule_id_dq_rules"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dq_results")),
    )
    op.create_index("ix_dq_results_rule_ts", "dq_results", ["rule_id", "ts"], unique=False)
    op.create_index(op.f("ix_dq_results_run_id"), "dq_results", ["run_id"], unique=False)
    op.add_column("datasets", sa.Column("domain", sa.String(length=128), nullable=True))
    op.create_index(op.f("ix_datasets_domain"), "datasets", ["domain"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_datasets_domain"), table_name="datasets")
    op.drop_column("datasets", "domain")
    op.drop_index(op.f("ix_dq_results_run_id"), table_name="dq_results")
    op.drop_index("ix_dq_results_rule_ts", table_name="dq_results")
    op.drop_table("dq_results")
    op.drop_index("uq_tag_assignments_target", table_name="tag_assignments")
    op.drop_index(op.f("ix_tag_assignments_tag"), table_name="tag_assignments")
    op.drop_index(op.f("ix_tag_assignments_dataset_id"), table_name="tag_assignments")
    op.drop_table("tag_assignments")
    op.drop_index(op.f("ix_row_filters_dataset_id"), table_name="row_filters")
    op.drop_table("row_filters")
    op.drop_index(op.f("ix_masking_policies_tag"), table_name="masking_policies")
    op.drop_table("masking_policies")
    op.drop_table("glossary_links")
    op.drop_index("ix_dq_scorecard_results_card_ts", table_name="dq_scorecard_results")
    op.drop_table("dq_scorecard_results")
    op.drop_index(op.f("ix_dq_rules_dataset_id"), table_name="dq_rules")
    op.drop_table("dq_rules")
    op.drop_table("tags")
    op.drop_table("notification_channels")
    op.drop_table("glossary_terms")
    op.drop_table("dq_scorecards")
    op.drop_index("uq_access_grants", table_name="access_grants")
    op.drop_table("access_grants")
    # ### end Alembic commands ###
